#!/usr/bin/env python3

import sys
import os
import shutil

"""
Lazy script to tidy up known_hosts file when keys change.
Just paste the complaint line from ssh into the command line.
"""

tempfile = "newfile.txt"

def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} ED25519 key in /Users/USERNAME/.ssh/known_hosts:XXX")
        sys.exit(1)

    filenameline = sys.argv[4]
    (filename,linenum) = filenameline.split(":")

    print(f"filename: {filename}")
    print(f"linenum: {linenum}")
    if not os.path.isfile(filename):
        print("{} is not a file".format(filename))
        sys.exit(1)


    with open(filename, "r") as file_input:
        with open(tempfile, "w") as output: 
            count = 0
            for line in file_input:
                count += 1
                if count == int(linenum):
                    print("Found line to remove")
                    print(line)
                    continue
                else:
                    output.write(line)

    shutil.copy2(tempfile, filename)

if __name__ == "__main__":
    main()
